apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app.name }}-service"
  namespace: default
spec:
  selector:
    app: "{{ .Values.app.name }}"
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: fs-fe-port
    protocol: TCP

